FROM ubuntu:20.04

RUN useradd --no-create-home -d /usr/share/tomcat tomcat

RUN apt-get update

RUN apt install default-jdk curl -y

RUN java --version

WORKDIR /opt/

RUN curl -O http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz

RUN tar xvf apache-tomcat-9.0.67.tar.gz

RUN ln -sfn /opt/apache-tomcat-9.0.67 /usr/share/tomcat

RUN chown -R tomcat:tomcat /usr/share/tomcat

ADD data/restro.war /usr/share/tomcat/webapps

EXPOSE 8080

CMD ["/usr/share/tomcat/bin/catalina.sh", "run"]
